#pragma once

#include "Document.h"
#include "Project.h"

#include <optional>
#include <string>
#include <variant>
#include <vector>

enum class TrimEdge { Head, Tail };

enum class EditError {
    None,
    UnknownTrack,
    UnknownClip,
    UnknownSource,
    UnknownBin,
    UnknownMarker,
    UnknownTransition,
    UnknownCaptionStyle,
    UnknownMulticamGroup,
    UnknownMulticamAngle,
    UnknownSequence,
    UnknownMedia,
    InvalidDuration,
    InvalidTimelineIn,
    SourceOutOfBounds,
    Overlap,
    DuplicateId,
    ArithmeticError,
    InvalidOperation,
    LockedTrack,
    ValidationFailed,
    EmptyUndo,
    EmptyRedo,
    IoError,
    ParseError,
};

const char* EditErrorName(EditError error);

struct ExactTimelinePosition {
    Ulid clip_id;
    RationalTime timeline_in;
};

struct ExactClipTimes {
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;
};

struct InsertClipOperation {
    Ulid track_id;
    Ulid source_id;
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;

    // Empty on first application; generated by ApplyOperation and retained for
    // redo/inverse identity.
    Ulid clip_id;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct RemoveClipOperation {
    Ulid clip_id;
    // QC-2026-09 A5 -- tracks without the removed A/V member still need the
    // same ripple to preserve their downstream alignment.
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct TrimClipOperation {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
    std::optional<ExactClipTimes> exact_clip_result;
};

struct ExactTrackState {
    Ulid track_id;
    std::vector<DocumentClip> clips;
};

struct PastedClip {
    // IDs from the copied selection are used only to rebuild links between the
    // new clips. clip_id and link_group_id are generated on first apply.
    Ulid copied_clip_id;
    Ulid track_id;
    Ulid source_id;
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;
    Ulid clip_id;
    Ulid copied_link_group_id;
    Ulid link_group_id;
    Ulid copied_sync_anchor_clip_id;
    Ulid sync_anchor_clip_id;
    RationalTime sync_reference_delta{0, 1};
};

struct PasteClipsOperation {
    std::vector<PastedClip> clips;
    std::vector<ExactTrackState> exact_track_result;
    bool overwrite = false;
};

struct ClearClipOperation {
    Ulid clip_id;
    std::vector<ExactTrackState> exact_track_result;
};

// One non-ripple delete gesture over an arbitrary selection is one atomic
// event. Unlike ClearLinkedClips, members need not share an A/V link group.
struct ClearClipsOperation {
    std::vector<Ulid> clip_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct MoveClipOperation {
    Ulid clip_id;
    Ulid track_id;
    RationalTime timeline_in;

    // Empty for a new move. ApplyOperation records the exact resulting tracks
    // so redo retains IDs created by an overwrite split. Inverse operations
    // carry the corresponding exact pre-move tracks.
    std::vector<ExactTrackState> exact_track_result;
};

struct LinkedClipMove {
    Ulid clip_id;
    Ulid track_id;
    RationalTime timeline_in;
};

// UI-2026-08 -- dragging an arbitrary timeline selection is one intention and
// therefore one undoable operation. Members need not share an A/V link group;
// each keeps its stable clip ID and receives an exact destination.
struct MoveClipsOperation {
    std::vector<LinkedClipMove> moves;
    std::vector<ExactTrackState> exact_track_result;
};

struct MoveLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<LinkedClipMove> moves;
    std::vector<ExactTrackState> exact_track_result;
};

struct LinkedClipTrim {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
};

// One trim gesture over linked A/V is one event-log entry. Exact track
// snapshots make redo/undo deterministic and guarantee all-or-nothing apply.
struct TrimLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<LinkedClipTrim> trims;
    std::vector<ExactTrackState> exact_track_result;
};

struct RippleTrimOperation {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Tail;
    RationalTime delta;
    std::vector<Ulid> linked_clip_ids;
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTrackState> exact_track_result;
};

// B4 -- ROADMAP.md. One measured boundary trim, already resolved to the
// exact delta ApplyRippleTrim understands. Keeping the linked members beside
// each boundary matters at a junction: the outgoing and incoming clips have
// different A/V groups, while the whole gesture must still be one event-log
// entry.
struct BoundaryAirTrim {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
    std::vector<Ulid> linked_clip_ids;
};

// Applies one clip's head/tail cleanup, or both sides of a junction,
// atomically. The exact snapshots are both the rollback representation and
// the canonical inverse, matching the other multi-track operations.
struct TrimBoundaryAirOperation {
    std::vector<BoundaryAirTrim> trims;
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct RollEditPair {
    Ulid left_clip_id;
    Ulid right_clip_id;
};

struct RollEditOperation {
    std::vector<RollEditPair> pairs;
    RationalTime delta;
    std::vector<ExactTrackState> exact_track_result;
};

// Slides source material underneath fixed timeline rectangles. Linked A/V
// members remain separate clips and receive the same exact source delta.
struct SlipEditOperation {
    std::vector<Ulid> clip_ids;
    RationalTime delta;
    std::vector<ExactTrackState> exact_track_result;
};

struct RemoveLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct ClearLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct DeleteGapOperation {
    Ulid track_id;
    RationalTime gap_start;
    RationalTime gap_duration;
    std::vector<ExactTrackState> exact_track_result;
    // Additional tracks shifted by the same duration when linked selection is
    // enabled. The primary track remains in track_id for compatibility.
    std::vector<Ulid> linked_track_ids;
};

struct DetachAudioOperation {
    Ulid video_clip_id;
    Ulid audio_track_id;
    Ulid audio_clip_id;
    std::vector<ExactTrackState> exact_track_result;
};

struct AddTrackOperation {
    Ulid track_id;
    std::string kind = "video";
    int32_t index = -1;
    // Populated by the inverse of RemoveTrack so undo restores its contents.
    std::vector<DocumentClip> clips;
    bool locked = false;
    bool sync_lock = true;
    bool visible = true;
    bool muted = false;
    bool solo = false;
};

struct UpdateSequenceOperation {
    Ulid sequence_id;
    std::string name;
    int32_t width = 1920;
    int32_t height = 1080;
    MediaRate frame_rate{25, 1};
};

// COLOR-2026-08 -- project color is authoritative document state, so UI,
// CLI, and MCP must all change it through the same reversible operation.
struct SetColorManagementOperation {
    ColorManagementSettings settings;
};

struct RemoveTrackOperation {
    Ulid track_id;
};

struct SetTrackLockOperation {
    Ulid track_id;
    bool locked = false;
};

struct SetTrackSyncLockOperation {
    Ulid track_id;
    bool sync_lock = true;
};

struct SetTrackOutputOperation {
    Ulid track_id;
    bool visible = true;
    bool muted = false;
    bool solo = false;
};

struct AddBinOperation {
    Ulid bin_id;
    std::string name;
    Ulid parent_id;
};

struct RemoveBinOperation {
    Ulid bin_id;
    // Filled for the inverse/redo path so the stable ID and name survive.
    std::string name;
    Ulid parent_id;
};

struct RenameBinOperation {
    Ulid bin_id;
    std::string name;
};

struct MoveBinOperation {
    Ulid bin_id;
    // Empty moves the bin to the top level.
    Ulid parent_id;
};

struct SetMediaBinOperation {
    Ulid media_id;
    // Empty assigns the media to the project root.
    Ulid bin_id;
};

struct AddMarkerOperation {
    DocumentMarker marker;
    // -1 appends on first application. Exact inverse operations carry the
    // original vector position so remove/undo restores canonical bytes.
    int64_t insertion_index = -1;
};

struct RemoveMarkerOperation {
    Ulid marker_id;
};

struct UpdateMarkerOperation {
    Ulid marker_id;
    std::string name;
    RationalTime time;
    std::string color;
    std::string category;
};

struct AddTransitionOperation {
    DocumentTransition transition;
    // -1 appends; inverse operations retain the exact sequence position.
    int64_t insertion_index = -1;
};

struct RemoveTransitionOperation {
    Ulid transition_id;
};

struct UpdateTransitionOperation {
    Ulid transition_id;
    std::string type = "cross_dissolve";
    RationalTime duration;
    TransitionAlignment alignment = TransitionAlignment::Center;
};

struct SetClipLinkOperation {
    Ulid first_clip_id;
    Ulid second_clip_id;
    Ulid first_group_id;
    Ulid second_group_id;
    struct ExactState {
        Ulid group_id;
        Ulid anchor_clip_id;
        RationalTime reference_delta{0, 1};
    };
    std::optional<ExactState> exact_first_result;
    std::optional<ExactState> exact_second_result;
};

struct SplitClipOperation {
    Ulid clip_id;
    RationalTime timeline_position;

    // Generated on first application and retained for redo identity.
    Ulid right_clip_id;
    // One per entry in the split clip's effect stack, in the same order.
    // Both halves of a cut keep the grade, but a ClipEffect's id lives in
    // the document's one ID space, so the right half needs its own -- and
    // they have to be the same on redo as on first application, exactly
    // like right_clip_id. Empty until the first application, or when the
    // clip carries no effects.
    std::vector<Ulid> right_effect_ids;
};

// A linked cut splits every A/V member at the same timeline position and gives
// each resulting side its own link group. Exact snapshots keep the gesture
// atomic and make undo/redo deterministic.
struct SplitLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    RationalTime timeline_position;
    Ulid left_group_id;
    Ulid right_group_id;
    std::vector<Ulid> right_clip_ids;
    // Additional tracks receive an edit at the same exact position even
    // when they hold no member of the linked group.
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTrackState> exact_track_result;
};

// Subdivides one clip -- and every clip A/V-linked to it -- at several exact
// timeline positions, as one atomic gesture with one undo step.
//
// `positions` is never a spacing a caller converted into frames itself. See
// ResolveIntervalSplits below, the only intended producer: it is where "every
// three seconds" becomes exact positions in the sequence's timebase. Same
// division of labour as RemoveWordsOperation/ResolveWordRemoval, for the same
// reason -- PHILOSOPHY.md principle 7, the caller states the intent and the
// code computes the frames. A model asked to convert 3s at 24000/1001 will
// eventually be off by a frame, silently, once per cut.
//
// Why one operation instead of N SplitClip calls: an agent gets one round
// trip rather than one per cut (ChatSession caps a turn at a handful of tool
// round trips, so repetitive work used to die half-finished), and the editor
// gets one Cmd+Z for "cut every three seconds" -- which is one intention, not
// eighteen.
struct SplitClipAtPositionsOperation {
    Ulid clip_id;
    // Strictly increasing, each strictly inside the clip's own timeline span.
    // ApplyOperation re-validates this rather than trusting its producer.
    std::vector<RationalTime> positions;
    // Whole-track snapshots, as SplitLinkedClipsOperation uses: they make
    // redo byte-exact without the operation having to carry a generated ID
    // for every piece and every effect on it.
    std::vector<ExactTrackState> exact_track_result;
};

// JoinClip is the exact inverse stored by the event log for SplitClip. Keeping
// it explicit makes persisted undo/redo deterministic across timebases.
struct JoinClipOperation {
    Ulid left_clip_id;
    Ulid right_clip_id;
    ExactClipTimes joined_times;
};

// Replaces a clip's entire color-grade stack. Full-vector replacement keeps
// the operation trivially invertible, the same shape as UpdateMarker.
struct SetClipEffectsOperation {
    Ulid clip_id;
    std::vector<ClipEffect> effects;
};

// ALPHA-2026-08 -- per-clip opacity is independently addressable from the
// creative color stack and has a compact, byte-exact inverse.
struct SetClipOpacityOperation {
    Ulid clip_id;
    EffectParamValue opacity{1, 1};
};

// QC-2026-09 A7 -- one audible clip setting is one editorial decision. The
// complete replacement state makes its inverse byte-exact and leaves no
// partial gain/fade state for a caller to reconcile.
struct SetClipAudioOperation {
    Ulid clip_id;
    EffectParamValue gain_db{0, 1};
    RationalTime fade_in{0, 1};
    RationalTime fade_out{0, 1};
};

struct AddCaptionStyleOperation {
    CaptionStyle style;
    // -1 appends on first application. Exact inverse operations carry the
    // original vector position so remove/undo restores canonical bytes.
    int64_t insertion_index = -1;
};

struct RemoveCaptionStyleOperation {
    Ulid style_id;
};

// Joins or removes a clip from a caption run. An empty caption_group_id
// clears the clip's caption.
struct SetClipCaptionOperation {
    Ulid clip_id;
    Ulid caption_group_id;
    std::string caption_text;
};

// F1.5 ("Multicam"): register a new multicam group and its angles.
struct AddMulticamGroupOperation {
    MulticamGroup group;
    // -1 appends on first application, mirroring AddMarker/AddTransition.
    int64_t insertion_index = -1;
};

// Exact inverse of AddMulticamGroupOperation, following the Add/Remove
// convention used by markers, transitions and caption styles.
struct RemoveMulticamGroupOperation {
    Ulid group_id;
};

struct SetMulticamActiveAngleOperation {
    Ulid group_id;
    Ulid active_angle_id;
};

// One exact, already-resolved span to cut from a clip's own source range.
// [source_start, source_end) in the clip's own time domain (the same domain
// as DocumentClip::source_in/duration). Never built from a raw frame number
// a caller invented: see Transcription.h's ResolveWordRemoval, which is the
// only intended producer -- it turns transcript word indices (what an agent
// or UI can name) into these exact ranges (what the engine can cut),
// mirroring PHILOSOPHY.md principle 7.
struct WordRemovalRange {
    RationalTime source_start;
    RationalTime source_end;
};

// Removes one or more word-derived spans from a single clip's own source
// range and ripple-closes each cut, splitting the clip into the fragments
// that remain. See ApplyRemoveWords in Operations.cc for the exact fragment
// placement and padding rule (documented once, at the implementation).
struct RemoveWordsOperation {
    Ulid clip_id;
    // Sorted, non-overlapping, each fully inside the clip's own
    // [source_in, source_in+duration) span. ApplyOperation validates this
    // itself rather than trusting the resolver that built it.
    std::vector<WordRemovalRange> ranges;
    // Extra timeline space left unfilled between two fragments of this same
    // clip that used to be separated only by a removed range. Zero means the
    // fragments butt together exactly. Never applied at the clip's own head
    // or tail edge (see ApplyRemoveWords) -- there is no fragment on the
    // other side of those cuts to pad against.
    RationalTime gap_padding{0, 1};
    // Other clips cut by the exact same source ranges, each ripple-closed on
    // its own track, inside this one operation. This is how an A/V pair is
    // cleaned: picture and sound must lose the same frames or they drift,
    // and doing it as two operations would turn one editorial gesture into
    // two undo steps. Every named clip must contain every range in its own
    // source span, which is checked here rather than trusted.
    std::vector<Ulid> linked_clip_ids;
    // Other tracks ripple-shifted by this clip's same total delta, beyond
    // the tracks cut above. Mirrors RippleTrimOperation::sync_track_ids.
    std::vector<Ulid> sync_track_ids;
    std::vector<ExactTrackState> exact_track_result;
};

using Operation = std::variant<
    InsertClipOperation, RemoveClipOperation, ClearClipOperation,
    ClearClipsOperation, PasteClipsOperation, TrimClipOperation,
    MoveClipOperation, MoveClipsOperation, DeleteGapOperation,
    DetachAudioOperation, MoveLinkedClipsOperation, TrimLinkedClipsOperation,
    RippleTrimOperation, TrimBoundaryAirOperation, RollEditOperation,
    SlipEditOperation,
    RemoveLinkedClipsOperation, ClearLinkedClipsOperation, AddTrackOperation,
    RemoveTrackOperation, SetTrackLockOperation, SetTrackSyncLockOperation,
    SetTrackOutputOperation, UpdateSequenceOperation,
    SetColorManagementOperation, SplitClipOperation, SplitLinkedClipsOperation,
    JoinClipOperation, AddBinOperation, RemoveBinOperation, RenameBinOperation,
    MoveBinOperation, SetMediaBinOperation, AddMarkerOperation,
    RemoveMarkerOperation, UpdateMarkerOperation, AddTransitionOperation,
    RemoveTransitionOperation, UpdateTransitionOperation, SetClipLinkOperation,
    SetClipEffectsOperation, SetClipOpacityOperation, SetClipAudioOperation,
    AddCaptionStyleOperation, RemoveCaptionStyleOperation,
    SetClipCaptionOperation, AddMulticamGroupOperation,
    RemoveMulticamGroupOperation, SetMulticamActiveAngleOperation,
    RemoveWordsOperation, SplitClipAtPositionsOperation>;

// Turns a repeat spacing into the exact positions to cut `clipId` at:
// interval, 2*interval, ... for as long as they stay strictly inside the
// clip's own timeline span. This is the deterministic computation
// PHILOSOPHY.md principle 7 asks for -- the caller names *how often*
// (semantic, agent- or UI-sized), this resolves *which frames* (exact,
// code-guaranteed) -- and it is the only intended producer of
// SplitClipAtPositionsOperation::positions.
//
// `interval` is a duration, not a frame count: {3, 1} is three seconds
// whatever the sequence runs at. Refuses a non-positive interval, an unknown
// clip, and an interval so long that it would not cut the clip at all, rather
// than silently applying nothing.
bool ResolveIntervalSplits(const Document& document, const Ulid& clipId,
                           const RationalTime& interval,
                           SplitClipAtPositionsOperation& operation,
                           std::string& error);

// Other clips sharing `clip`'s A/V link group *and* genuinely covering the
// same cut. A word-level cut that touched only the clip it was aimed at
// would shorten the sound and leave the picture, so a detached A/V pair has
// to be cut together -- and working out which clips those are is a
// document-shape question the caller should not have to answer
// (PHILOSOPHY.md principle 7).
//
// The containment test is what keeps this an intent-layer decision rather
// than a guess. A link group can hold a member that reads from another
// source, or from another part of the same one; cutting it by these ranges
// would be meaningless, so it is left alone here. RemoveWordsOperation stays
// strict about whatever it is finally told: naming such a clip explicitly is
// still an error, it just is not one this resolver produces.
//
// QC-2026-09 (A2) -- lives here rather than in McpTools.cc, where it was
// written for Q4b, because pause tightening needs the same answer from both
// the CLI and the MCP surface. A rule about which clips a cut has to carry
// is engine knowledge; two copies of it would be two chances to drift.
std::vector<Ulid> LinkedClipIdsCoveringRanges(
    const Document& document, const DocumentClip& clip,
    const std::vector<WordRemovalRange>& ranges);

struct ExactProjectState {
    std::string canonical_json;
};

struct AddProjectTimelineOperation {
    std::string name = "New Timeline";
    int32_t width = 1920;
    int32_t height = 1080;
    MediaRate frame_rate{25, 1};
    Ulid timeline_id;
    Ulid video_track_id;
    Ulid audio_track_id;
    std::optional<ExactProjectState> exact_project_result;
};

// ALPHA-2026-08 -- An agent chooses editorial source ranges, while the engine
// owns the deterministic assembly, generated identities and exact timeline
// positions. This keeps a natural-language "make a short" request on the
// same reversible project-operation path as every other edit.
struct ProjectTimelineSourceSegment {
    Ulid source_id;
    RationalTime source_in;
    RationalTime duration;
    Ulid video_clip_id;
    Ulid audio_clip_id;
    Ulid link_group_id;
};

struct CreateProjectTimelineFromSegmentsOperation {
    std::string name = "Interview short";
    int32_t width = 1920;
    int32_t height = 1080;
    MediaRate frame_rate{25, 1};
    std::vector<ProjectTimelineSourceSegment> segments;
    Ulid timeline_id;
    Ulid video_track_id;
    Ulid audio_track_id;
    bool make_active = true;
    std::optional<ExactProjectState> exact_project_result;
};

struct RemoveProjectTimelineOperation {
    Ulid timeline_id;
    std::optional<ExactProjectState> exact_project_result;
};

struct SetProjectBinMetadataOperation {
    Ulid item_id;
    ProjectBinMetadata metadata;
    std::optional<ExactProjectState> exact_project_result;
};

struct SetProjectTimelineBinOperation {
    Ulid timeline_id;
    Ulid bin_id;
    std::optional<ExactProjectState> exact_project_result;
};

struct RenameProjectItemOperation {
    Ulid item_id;
    std::string name;
    std::optional<ExactProjectState> exact_project_result;
};

struct ProjectRelinkItem {
    Ulid media_id;
    LibraryMedia replacement;
    std::string stored_path;
};

// QC-2026-08 -- Switching which timeline is active was reachable only from
// the app's own timeline list, so an agent could create a timeline and then
// not navigate to one. That is the "moteur d'abord" rule broken in the
// direction the rule exists to prevent (PHILOSOPHY.md principle 3): a
// capability the mouse had and no other surface did.
struct SetActiveProjectTimelineOperation {
    Ulid timeline_id;
    std::optional<ExactProjectState> exact_project_result;
};

struct RelinkProjectMediaOperation {
    std::vector<ProjectRelinkItem> replacements;
    std::optional<ExactProjectState> exact_project_result;
};

using ProjectOperation = std::variant<
    AddProjectTimelineOperation, CreateProjectTimelineFromSegmentsOperation,
    RemoveProjectTimelineOperation, SetProjectBinMetadataOperation,
    SetProjectTimelineBinOperation, RenameProjectItemOperation,
    SetActiveProjectTimelineOperation, RelinkProjectMediaOperation>;

// On success, operation is enriched with generated IDs and exact redo state.
// Both document and operation remain unchanged on failure.
bool ApplyOperation(Document& document, Operation& operation,
                    Operation& inverse, EditError& error, std::string& message);

bool ApplyProjectOperation(Project& project, ProjectOperation& operation,
                           ProjectOperation& inverse, EditError& error,
                           std::string& message);

std::string SerializeOperation(const Operation& operation);
bool DeserializeOperation(const std::string& json, Operation& operation,
                          EditError& error, std::string& message);

std::string SerializeProjectOperation(const ProjectOperation& operation);
bool DeserializeProjectOperation(const std::string& json,
                                 ProjectOperation& operation, EditError& error,
                                 std::string& message);
