#pragma once

#include "Document.h"

#include <optional>
#include <string>
#include <variant>
#include <vector>

enum class TrimEdge { Head, Tail };

enum class EditError {
    None,
    UnknownTrack,
    UnknownClip,
    UnknownSource,
    InvalidDuration,
    InvalidTimelineIn,
    SourceOutOfBounds,
    Overlap,
    DuplicateId,
    ArithmeticError,
    InvalidOperation,
    ValidationFailed,
    EmptyUndo,
    EmptyRedo,
    IoError,
    ParseError,
};

const char* EditErrorName(EditError error);

struct ExactTimelinePosition {
    Ulid clip_id;
    RationalTime timeline_in;
};

struct ExactClipTimes {
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;
};

struct InsertClipOperation {
    Ulid track_id;
    Ulid source_id;
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;

    // Empty on first application; generated by ApplyOperation and retained for
    // redo/inverse identity.
    Ulid clip_id;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct RemoveClipOperation {
    Ulid clip_id;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct TrimClipOperation {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
    std::optional<ExactClipTimes> exact_clip_result;
};

using Operation =
    std::variant<InsertClipOperation, RemoveClipOperation, TrimClipOperation>;

// On success, operation is enriched with generated IDs and exact redo state.
// Both document and operation remain unchanged on failure.
bool ApplyOperation(Document& document, Operation& operation,
                    Operation& inverse, EditError& error, std::string& message);

std::string SerializeOperation(const Operation& operation);
bool DeserializeOperation(const std::string& json, Operation& operation,
                          EditError& error, std::string& message);
