#pragma once

#include "Document.h"

#include <optional>
#include <string>
#include <variant>
#include <vector>

enum class TrimEdge { Head, Tail };

enum class EditError {
    None,
    UnknownTrack,
    UnknownClip,
    UnknownSource,
    UnknownBin,
    UnknownMarker,
    UnknownSequence,
    UnknownMedia,
    InvalidDuration,
    InvalidTimelineIn,
    SourceOutOfBounds,
    Overlap,
    DuplicateId,
    ArithmeticError,
    InvalidOperation,
    ValidationFailed,
    EmptyUndo,
    EmptyRedo,
    IoError,
    ParseError,
};

const char* EditErrorName(EditError error);

struct ExactTimelinePosition {
    Ulid clip_id;
    RationalTime timeline_in;
};

struct ExactClipTimes {
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;
};

struct InsertClipOperation {
    Ulid track_id;
    Ulid source_id;
    RationalTime source_in;
    RationalTime duration;
    RationalTime timeline_in;

    // Empty on first application; generated by ApplyOperation and retained for
    // redo/inverse identity.
    Ulid clip_id;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct RemoveClipOperation {
    Ulid clip_id;
    std::vector<ExactTimelinePosition> exact_timeline_result;
};

struct TrimClipOperation {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
    std::optional<ExactClipTimes> exact_clip_result;
};

struct ExactTrackState {
    Ulid track_id;
    std::vector<DocumentClip> clips;
};

struct ClearClipOperation {
    Ulid clip_id;
    std::vector<ExactTrackState> exact_track_result;
};

struct MoveClipOperation {
    Ulid clip_id;
    Ulid track_id;
    RationalTime timeline_in;

    // Empty for a new move. ApplyOperation records the exact resulting tracks
    // so redo retains IDs created by an overwrite split. Inverse operations
    // carry the corresponding exact pre-move tracks.
    std::vector<ExactTrackState> exact_track_result;
};

struct LinkedClipMove {
    Ulid clip_id;
    Ulid track_id;
    RationalTime timeline_in;
};

struct MoveLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<LinkedClipMove> moves;
    std::vector<ExactTrackState> exact_track_result;
};

struct LinkedClipTrim {
    Ulid clip_id;
    TrimEdge edge = TrimEdge::Head;
    RationalTime delta;
};

// One trim gesture over linked A/V is one event-log entry. Exact track
// snapshots make redo/undo deterministic and guarantee all-or-nothing apply.
struct TrimLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<LinkedClipTrim> trims;
    std::vector<ExactTrackState> exact_track_result;
};

struct RemoveLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct ClearLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    std::vector<ExactTrackState> exact_track_result;
};

struct DeleteGapOperation {
    Ulid track_id;
    RationalTime gap_start;
    RationalTime gap_duration;
    std::vector<ExactTrackState> exact_track_result;
    // Additional tracks shifted by the same duration when linked selection is
    // enabled. The primary track remains in track_id for compatibility.
    std::vector<Ulid> linked_track_ids;
};

struct DetachAudioOperation {
    Ulid video_clip_id;
    Ulid audio_track_id;
    Ulid audio_clip_id;
    std::vector<ExactTrackState> exact_track_result;
};

struct AddTrackOperation {
    Ulid track_id;
    std::string kind = "video";
    int32_t index = -1;
    // Populated by the inverse of RemoveTrack so undo restores its contents.
    std::vector<DocumentClip> clips;
};

struct UpdateSequenceOperation {
    Ulid sequence_id;
    std::string name;
    int32_t width = 1920;
    int32_t height = 1080;
    MediaRate frame_rate{25, 1};
};

struct RemoveTrackOperation {
    Ulid track_id;
};

struct AddBinOperation {
    Ulid bin_id;
    std::string name;
    Ulid parent_id;
};

struct RemoveBinOperation {
    Ulid bin_id;
    // Filled for the inverse/redo path so the stable ID and name survive.
    std::string name;
    Ulid parent_id;
};

struct RenameBinOperation {
    Ulid bin_id;
    std::string name;
};

struct MoveBinOperation {
    Ulid bin_id;
    // Empty moves the bin to the top level.
    Ulid parent_id;
};

struct SetMediaBinOperation {
    Ulid media_id;
    // Empty assigns the media to the project root.
    Ulid bin_id;
};

struct AddMarkerOperation {
    DocumentMarker marker;
    // -1 appends on first application. Exact inverse operations carry the
    // original vector position so remove/undo restores canonical bytes.
    int64_t insertion_index = -1;
};

struct RemoveMarkerOperation {
    Ulid marker_id;
};

struct UpdateMarkerOperation {
    Ulid marker_id;
    std::string name;
    RationalTime time;
    std::string color;
    std::string category;
};

struct SetClipLinkOperation {
    Ulid first_clip_id;
    Ulid second_clip_id;
    Ulid first_group_id;
    Ulid second_group_id;
    struct ExactState {
        Ulid group_id;
        Ulid anchor_clip_id;
        RationalTime reference_delta{0, 1};
    };
    std::optional<ExactState> exact_first_result;
    std::optional<ExactState> exact_second_result;
};

struct SplitClipOperation {
    Ulid clip_id;
    RationalTime timeline_position;

    // Generated on first application and retained for redo identity.
    Ulid right_clip_id;
};

// A linked cut splits every A/V member at the same timeline position and gives
// each resulting side its own link group. Exact snapshots keep the gesture
// atomic and make undo/redo deterministic.
struct SplitLinkedClipsOperation {
    Ulid link_group_id;
    std::vector<Ulid> clip_ids;
    RationalTime timeline_position;
    Ulid left_group_id;
    Ulid right_group_id;
    std::vector<Ulid> right_clip_ids;
    std::vector<ExactTrackState> exact_track_result;
};

// JoinClip is the exact inverse stored by the event log for SplitClip. Keeping
// it explicit makes persisted undo/redo deterministic across timebases.
struct JoinClipOperation {
    Ulid left_clip_id;
    Ulid right_clip_id;
    ExactClipTimes joined_times;
};

using Operation =
    std::variant<InsertClipOperation, RemoveClipOperation, ClearClipOperation,
                 TrimClipOperation,
                 MoveClipOperation, DeleteGapOperation, DetachAudioOperation,
                 MoveLinkedClipsOperation, TrimLinkedClipsOperation,
                 RemoveLinkedClipsOperation, ClearLinkedClipsOperation,
                 AddTrackOperation,
                 RemoveTrackOperation, UpdateSequenceOperation,
                 SplitClipOperation, SplitLinkedClipsOperation,
                 JoinClipOperation,
                 AddBinOperation, RemoveBinOperation, RenameBinOperation,
                 MoveBinOperation, SetMediaBinOperation, AddMarkerOperation,
                 RemoveMarkerOperation, UpdateMarkerOperation,
                 SetClipLinkOperation>;

// On success, operation is enriched with generated IDs and exact redo state.
// Both document and operation remain unchanged on failure.
bool ApplyOperation(Document& document, Operation& operation,
                    Operation& inverse, EditError& error, std::string& message);

std::string SerializeOperation(const Operation& operation);
bool DeserializeOperation(const std::string& json, Operation& operation,
                          EditError& error, std::string& message);
