#pragma once

#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <vector>

#include "EditLog.h"
#include "Project.h"

class ProjectSessionLock {
public:
    ProjectSessionLock();
    ~ProjectSessionLock();
    ProjectSessionLock(const ProjectSessionLock&) = delete;
    ProjectSessionLock& operator=(const ProjectSessionLock&) = delete;

    bool Acquire(const std::string& projectPath, std::string& owner,
                 std::string& error);
    void Release();
    bool Held() const;

private:
    std::string lock_directory_;
    std::string token_;
};

struct CollectionIntegrityReport {
    uint64_t verified_media = 0;
    std::vector<std::string> missing_media;
    std::vector<std::string> modified_media;
};

// Returns success when the manifest was parsed and checked. Integrity failures
// are reported in the result rather than as I/O/parser errors.
bool VerifyPortableProject(const std::string& projectPath,
                           CollectionIntegrityReport& report,
                           std::string& error);

bool IsPortableProjectV2(const std::string& projectPath);
bool CreatePortableProject(const std::string& destinationDirectory,
                           const Project& project, std::string& projectPath,
                           std::string& error);
bool LoadStoredProject(const std::string& projectPath, Project& project,
                       std::string& error);
bool CommitStoredProject(const std::string& projectPath, const Project& project,
                         std::string& error);
// B10 -- ROADMAP.md. timelineLogs is a partial write set: an omitted existing
// journal stays byte-identical on disk, while a newly added timeline receives
// an empty journal. This lets project-only edits avoid reading every timeline
// history before an otherwise unrelated commit.
bool CommitStoredProjectAndLogs(
    const std::string& projectPath, const Project& project,
    const std::map<std::string, EditLog>& timelineLogs,
    const ProjectEditLog& projectLog, std::string& error);

struct PortableProjectResult {
    std::string directory_path;
    std::string project_path;
    uint64_t media_count = 0;
    uint64_t media_bytes = 0;
};

// Creates an autonomous project directory without mutating the source. The
// destination must not exist. All original media must be readable; derived
// caches are deliberately excluded and will be regenerated by the receiver.
bool CollectPortableProject(const std::string& sourceProjectPath,
                            const std::string& destinationDirectory,
                            PortableProjectResult& result, std::string& error);
