name: build

on:
  push:
  pull_request:

jobs:
  cmake-build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ffmpeg pkg-config cmake

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build --parallel
